probamex-rails:
    image: rails:5.0.0.1
    hostname: probamexRails
    container_name: probamexRails
    ports:
        - "3000:3000"
    volumes:
        - ./src:/usr/src/app
    working_dir: /usr/src/app
    command: [ "rails", "server", "-b", "0.0.0.0" ]
    entrypoint: ./postinstall.sh
